/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package congklak;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author mmdiyul
 */
public class Congklak extends javax.swing.JFrame {
    
    private int currentPlayer;
    private int sizeHome1, sizeHome2, sizeHome3, sizeHome4, sizeHome5,
            sizeAway1, sizeAway2, sizeAway3, sizeAway4, sizeAway5;
    private boolean statusHome1, statusHome2, statusHome3, statusHome4, statusHome5,
            statusAway1, statusAway2, statusAway3, statusAway4, statusAway5,
            statusScoreHome, statusScoreAway;
    private int onHand;
    private int scoreHome, scoreAway;

    /**
     * Creates new form Congklak
     */
    public Congklak() {
        initComponents();
        sizeAway1 = 5;
        sizeAway2 = 5;
        sizeAway3 = 5;
        sizeAway4 = 5;
        sizeAway5 = 5;
        sizeHome1 = 5;
        sizeHome2 = 5;
        sizeHome3 = 5;
        sizeHome4 = 5;
        sizeHome5 = 5;
        scoreHome = 0;
        scoreAway = 0;
        setTrue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home1 = new javax.swing.JButton();
        home2 = new javax.swing.JButton();
        home3 = new javax.swing.JButton();
        home4 = new javax.swing.JButton();
        home5 = new javax.swing.JButton();
        away3 = new javax.swing.JButton();
        away4 = new javax.swing.JButton();
        away5 = new javax.swing.JButton();
        away2 = new javax.swing.JButton();
        away1 = new javax.swing.JButton();
        homeScore = new javax.swing.JLabel();
        awayScore = new javax.swing.JLabel();
        buttonSuit = new javax.swing.JButton();
        textPlayer = new javax.swing.JLabel();
        buttonRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        home1.setText("5");
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });

        home2.setText("5");
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });

        home3.setText("5");
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });

        home4.setText("5");
        home4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home4ActionPerformed(evt);
            }
        });

        home5.setText("5");
        home5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home5ActionPerformed(evt);
            }
        });

        away3.setText("5");
        away3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away3ActionPerformed(evt);
            }
        });

        away4.setText("5");
        away4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away4ActionPerformed(evt);
            }
        });

        away5.setText("5");
        away5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away5ActionPerformed(evt);
            }
        });

        away2.setText("5");
        away2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away2ActionPerformed(evt);
            }
        });

        away1.setText("5");
        away1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                away1ActionPerformed(evt);
            }
        });

        homeScore.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        homeScore.setText("0");

        awayScore.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        awayScore.setText("0");

        buttonSuit.setText("Suit");
        buttonSuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuitActionPerformed(evt);
            }
        });

        buttonRestart.setText("Restart");
        buttonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(away1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(away2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(away3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(away4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(away5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(home1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(home2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(home3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(home4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(home5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(awayScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeScore))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSuit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(away1)
                    .addComponent(away2)
                    .addComponent(away3)
                    .addComponent(away4)
                    .addComponent(away5))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeScore)
                    .addComponent(awayScore))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home1)
                    .addComponent(home2)
                    .addComponent(home3)
                    .addComponent(home4)
                    .addComponent(home5))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSuit)
                    .addComponent(textPlayer)
                    .addComponent(buttonRestart))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTrue() {
        statusAway1 = true;
        statusAway2 = true;
        statusAway3 = true;
        statusAway4 = true;
        statusAway5 = true;
        statusHome1 = true;
        statusHome2 = true;
        statusHome3 = true;
        statusHome4 = true;
        statusHome5 = true;
        statusScoreAway = true;
        statusScoreHome = true;
    }
    
    private void runHome() {
        if (onHand != 0) {
            if (statusHome1 == true) {
                sizeHome1++;
                onHand--;
                home1.setText(String.valueOf(sizeHome1));
                textPlayer.setText(String.valueOf(onHand));
                statusHome1 = false;
                if (onHand == 0 && sizeHome1 > 1) {
                    statusHome1 = false;
                    onHand = sizeHome1;
                    sizeHome1 = 0;
                    home1.setText(String.valueOf(sizeHome1));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeHome1 == 1) {
                    onHand = sizeHome1 + sizeAway1;
                    scoreHome = scoreHome + onHand;
                    homeScore.setText(String.valueOf(scoreHome));
                    onHand = 0;
                    sizeHome1 = 0;
                    sizeAway1 = 0;
                    home1.setText(String.valueOf(sizeHome1));
                    away1.setText(String.valueOf(sizeAway1));
                    textPlayer.setText("Giliran player 2");
                } 
            } else if (statusHome2 == true) {
                sizeHome2++;
                onHand--;
                home2.setText(String.valueOf(sizeHome2));
                textPlayer.setText(String.valueOf(onHand));
                statusHome2 = false;
                if (onHand == 0 && sizeHome2 > 1) {
                    statusHome2 = false;
                    onHand = sizeHome2;
                    sizeHome1 = 0;
                    home2.setText(String.valueOf(sizeHome2));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeHome2 == 1) {
                    onHand = sizeHome2 + sizeAway2;
                    scoreHome = scoreHome + onHand;
                    homeScore.setText(String.valueOf(scoreHome));
                    onHand = 0;
                    sizeHome2 = 0;
                    sizeAway2 = 0;
                    home2.setText(String.valueOf(sizeHome2));
                    away2.setText(String.valueOf(sizeAway2));
                    textPlayer.setText("Giliran player 2");
                } 
            } else if (statusHome3 == true) {
                sizeHome3++;
                onHand--;
                home3.setText(String.valueOf(sizeHome3));
                textPlayer.setText(String.valueOf(onHand));
                statusHome3 = false;
                if (onHand == 0 && sizeHome3 > 1) {
                    statusHome3 = false;
                    onHand = sizeHome3;
                    sizeHome3 = 0;
                    home3.setText(String.valueOf(sizeHome3));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeHome3 == 1) {
                    onHand = sizeHome3 + sizeAway3;
                    scoreHome = scoreHome + onHand;
                    homeScore.setText(String.valueOf(scoreHome));
                    onHand = 0;
                    sizeHome3 = 0;
                    sizeAway3 = 0;
                    home3.setText(String.valueOf(sizeHome3));
                    away3.setText(String.valueOf(sizeAway3));
                    textPlayer.setText("Giliran player 2");
                } 
            } else if (statusHome4 == true) {
                sizeHome4++;
                onHand--;
                home4.setText(String.valueOf(sizeHome4));
                textPlayer.setText(String.valueOf(onHand));
                statusHome4 = false;
                if (onHand == 0 && sizeHome4 > 1) {
                    statusHome4 = false;
                    onHand = sizeHome4;
                    sizeHome4 = 0;
                    home4.setText(String.valueOf(sizeHome4));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeHome4 == 1) {
                    onHand = sizeHome4 + sizeAway4;
                    scoreHome = scoreHome + onHand;
                    homeScore.setText(String.valueOf(scoreHome));
                    onHand = 0;
                    sizeHome4 = 0;
                    sizeAway4 = 0;
                    home4.setText(String.valueOf(sizeHome4));
                    away4.setText(String.valueOf(sizeAway4));
                    textPlayer.setText("Giliran player 2");
                }
            } else if (statusHome5 == true) {
                sizeHome5++;
                onHand--;
                home5.setText(String.valueOf(sizeHome5));
                textPlayer.setText(String.valueOf(onHand));
                statusHome5 = false;
                if (onHand == 0 && sizeHome5 > 1) {
                    statusHome5 = false;
                    onHand = sizeHome5;
                    sizeHome5 = 0;
                    home5.setText(String.valueOf(sizeHome5));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeHome5 == 1) {
                    onHand = sizeHome5 + sizeAway5;
                    scoreHome = scoreHome + onHand;
                    homeScore.setText(String.valueOf(scoreHome));
                    onHand = 0;
                    sizeHome5 = 0;
                    sizeAway5 = 0;
                    home5.setText(String.valueOf(sizeHome5));
                    away5.setText(String.valueOf(sizeAway5));
                    textPlayer.setText("Giliran player 2");
                } 
            } else if (statusScoreHome == true) {
                scoreHome++;
                onHand--;
                homeScore.setText(String.valueOf(scoreHome));
                textPlayer.setText(String.valueOf(onHand));
                statusScoreHome = false;
            } else if (statusAway5 == true) {
                sizeAway5++;
                onHand--;
                away5.setText(String.valueOf(sizeAway5));
                textPlayer.setText(String.valueOf(onHand));
                statusAway5 = false;
                if (onHand == 0 && sizeAway5 > 1) {
                    statusAway5 = false;
                    onHand = sizeAway5;
                    sizeAway5 = 0;
                    away5.setText(String.valueOf(sizeAway5));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeAway5 == 1) {
                    textPlayer.setText("Giliran player 2");
                }
            } else if (statusAway4 == true) {
                sizeAway4++;
                onHand--;
                away4.setText(String.valueOf(sizeAway4));
                textPlayer.setText(String.valueOf(onHand));
                statusAway4 = false;
                if (onHand == 0 && sizeAway4 > 1) {
                    statusAway4 = false;
                    onHand = sizeAway4;
                    sizeAway4 = 0;
                    away4.setText(String.valueOf(sizeAway4));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeAway4 == 1) {
                    textPlayer.setText("Giliran player 2");
                }
            } else if (statusAway3 == true) {
                sizeAway3++;
                onHand--;
                away3.setText(String.valueOf(sizeAway3));
                textPlayer.setText(String.valueOf(onHand));
                statusAway3 = false;
                if (onHand == 0 && sizeAway3 > 1) {
                    statusAway3 = false;
                    onHand = sizeAway3;
                    sizeAway3 = 0;
                    away3.setText(String.valueOf(sizeAway3));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeAway3 == 1) {
                    textPlayer.setText("Giliran player 2");
                }
            } else if (statusAway2 == true) {
                sizeAway2++;
                onHand--;
                away2.setText(String.valueOf(sizeAway2));
                textPlayer.setText(String.valueOf(onHand));
                statusAway2 = false;
                if (onHand == 0 && sizeAway2 > 1) {
                    statusAway2 = false;
                    onHand = sizeAway2;
                    sizeAway2 = 0;
                    away2.setText(String.valueOf(sizeAway2));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeAway2 == 1) {
                    textPlayer.setText("Giliran player 2");
                }
            } else if (statusAway1 == true) {
                sizeAway1++;
                onHand--;
                away1.setText(String.valueOf(sizeAway1));
                textPlayer.setText(String.valueOf(onHand));
                statusAway1 = false;
                if (onHand == 0 && sizeAway1 > 1) {
                    statusAway1 = false;
                    onHand = sizeAway1;
                    sizeAway1 = 0;
                    away1.setText(String.valueOf(sizeAway1));
                    textPlayer.setText(String.valueOf(onHand));
                } else if (onHand == 0 && sizeAway1 == 1) {
                    textPlayer.setText("Giliran player 2");
                }
            } else {
                setTrue();
            }
        }
    }
    
    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        // TODO add your handling code here:
        setTrue();
        statusHome1 = false;
        onHand = sizeHome1;
        sizeHome1 = 0;
        home1.setText(String.valueOf(sizeHome1));
        textPlayer.setText(String.valueOf(onHand));
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                runHome();
            }
        });
        timer.start();
        buttonRestart.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timer.stop();
            }
        });
    }//GEN-LAST:event_home1ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        // TODO add your handling code here:
        setTrue();
        statusHome1 = false;
        statusHome2 = false;
        onHand = sizeHome2;
        sizeHome2 = 0;
        home2.setText(String.valueOf(sizeHome2));
        textPlayer.setText(String.valueOf(onHand));
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                runHome();
            }
        });
        timer.start();
        buttonRestart.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timer.stop();
            }
        });
    }//GEN-LAST:event_home2ActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        // TODO add your handling code here:
        setTrue();
        statusHome1 = false;
        statusHome2 = false;
        statusHome3 = false;
        onHand = sizeHome3;
        sizeHome3 = 0;
        home3.setText(String.valueOf(sizeHome3));
        textPlayer.setText(String.valueOf(onHand));
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                runHome();
            }
        });
        timer.start();
        buttonRestart.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timer.stop();
            }
        });
    }//GEN-LAST:event_home3ActionPerformed

    private void home4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home4ActionPerformed
        // TODO add your handling code here:
        setTrue();
        statusHome1 = false;
        statusHome2 = false;
        statusHome3 = false;
        statusHome4 = false;
        onHand = sizeHome4;
        sizeHome4 = 0;
        home4.setText(String.valueOf(sizeHome4));
        textPlayer.setText(String.valueOf(onHand));
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                runHome();
            }
        });
        timer.start();
        buttonRestart.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timer.stop();
            }
        });
    }//GEN-LAST:event_home4ActionPerformed

    private void home5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home5ActionPerformed
        // TODO add your handling code here:
        setTrue();
        statusHome1 = false;
        statusHome2 = false;
        statusHome3 = false;
        statusHome4 = false;
        statusHome5 = false;
        onHand = sizeHome5;
        sizeHome5 = 0;
        home5.setText(String.valueOf(sizeHome5));
        textPlayer.setText(String.valueOf(onHand));
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                runHome();
            }
        });
        timer.start();
        buttonRestart.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timer.stop();
            }
        });
    }//GEN-LAST:event_home5ActionPerformed

    private void away3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_away3ActionPerformed

    private void away4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_away4ActionPerformed

    private void away5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_away5ActionPerformed

    private void away2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_away2ActionPerformed

    private void away1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_away1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_away1ActionPerformed

    private void buttonSuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuitActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        currentPlayer = random.nextInt(2);
        if (currentPlayer == 0) {
            textPlayer.setText("Player 1 Main duluan!");
            away1.setText(String.valueOf(sizeAway1));
            away2.setText(String.valueOf(sizeAway2));
            away3.setText(String.valueOf(sizeAway3));
            away4.setText(String.valueOf(sizeAway4));
            away5.setText(String.valueOf(sizeAway5));
            home1.setText(String.valueOf(sizeHome1));
            home2.setText(String.valueOf(sizeHome2));
            home3.setText(String.valueOf(sizeHome3));
            home4.setText(String.valueOf(sizeHome4));
            home5.setText(String.valueOf(sizeHome5));
            awayScore.setText(String.valueOf(scoreAway));
            homeScore.setText(String.valueOf(scoreHome));
            away1.setEnabled(false);
            away2.setEnabled(false);
            away3.setEnabled(false);
            away4.setEnabled(false);
            away5.setEnabled(false);
            home1.setEnabled(true);
            home2.setEnabled(true);
            home3.setEnabled(true);
            home4.setEnabled(true);
            home5.setEnabled(true);
        } else {
            textPlayer.setText("Player 2 Main duluan!");
            away1.setText(String.valueOf(sizeAway1));
            away2.setText(String.valueOf(sizeAway2));
            away3.setText(String.valueOf(sizeAway3));
            away4.setText(String.valueOf(sizeAway4));
            away5.setText(String.valueOf(sizeAway5));
            home1.setText(String.valueOf(sizeHome1));
            home2.setText(String.valueOf(sizeHome2));
            home3.setText(String.valueOf(sizeHome3));
            home4.setText(String.valueOf(sizeHome4));
            home5.setText(String.valueOf(sizeHome5));
            awayScore.setText(String.valueOf(scoreAway));
            homeScore.setText(String.valueOf(scoreHome));
            away1.setEnabled(false);
            away2.setEnabled(false);
            away3.setEnabled(false);
            away4.setEnabled(false);
            away5.setEnabled(false);
            home1.setEnabled(false);
            home2.setEnabled(false);
            home3.setEnabled(false);
            home4.setEnabled(false);
            home5.setEnabled(false);
        }
        buttonSuit.setEnabled(false);
    }//GEN-LAST:event_buttonSuitActionPerformed

    private void buttonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestartActionPerformed
        // TODO add your handling code here:
        buttonSuit.setEnabled(true);
        textPlayer.setText("");
        away1.setEnabled(false);
        away2.setEnabled(false);
        away3.setEnabled(false);
        away4.setEnabled(false);
        away5.setEnabled(false);
        home1.setEnabled(false);
        home2.setEnabled(false);
        home3.setEnabled(false);
        home4.setEnabled(false);
        home5.setEnabled(false);
        sizeAway1 = 5;
        sizeAway2 = 5;
        sizeAway3 = 5;
        sizeAway4 = 5;
        sizeAway5 = 5;
        sizeHome1 = 5;
        sizeHome2 = 5;
        sizeHome3 = 5;
        sizeHome4 = 5;
        sizeHome5 = 5;
        scoreHome = 0;
        scoreAway = 0;
        away1.setText(String.valueOf(sizeAway1));
        away2.setText(String.valueOf(sizeAway2));
        away3.setText(String.valueOf(sizeAway3));
        away4.setText(String.valueOf(sizeAway4));
        away5.setText(String.valueOf(sizeAway5));
        home1.setText(String.valueOf(sizeHome1));
        home2.setText(String.valueOf(sizeHome2));
        home3.setText(String.valueOf(sizeHome3));
        home4.setText(String.valueOf(sizeHome4));
        home5.setText(String.valueOf(sizeHome5));
        homeScore.setText(String.valueOf(scoreHome));
        awayScore.setText(String.valueOf(scoreAway));
    }//GEN-LAST:event_buttonRestartActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        away1.setEnabled(false);
        away2.setEnabled(false);
        away3.setEnabled(false);
        away4.setEnabled(false);
        away5.setEnabled(false);
        home1.setEnabled(false);
        home2.setEnabled(false);
        home3.setEnabled(false);
        home4.setEnabled(false);
        home5.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Congklak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Congklak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Congklak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congklak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Congklak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton away1;
    private javax.swing.JButton away2;
    private javax.swing.JButton away3;
    private javax.swing.JButton away4;
    private javax.swing.JButton away5;
    private javax.swing.JLabel awayScore;
    private javax.swing.JButton buttonRestart;
    private javax.swing.JButton buttonSuit;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JButton home3;
    private javax.swing.JButton home4;
    private javax.swing.JButton home5;
    private javax.swing.JLabel homeScore;
    private javax.swing.JLabel textPlayer;
    // End of variables declaration//GEN-END:variables
}
